import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from 'react-router-dom';
const Home = () => {
    return (_jsxs("div", { className: "min-h-screen bg-slate-50", children: [" ", _jsx("div", { className: "absolute top-0 left-0 right-0 h-[450px] sm:h-[520px] bg-cover bg-center bg-no-repeat" // Increased mobile height to 450px for more text space
                , style: { backgroundImage: 'url(/bio/bg.jpg)' }, children: _jsx("div", { className: "absolute inset-0 bg-gradient-to-br from-black/75 via-black/70 to-black/65" }) }), _jsx("div", { className: "relative z-10 pt-16 sm:pt-20", children: _jsxs("div", { className: "max-w-6xl mx-auto px-4 sm:px-6 py-8 sm:py-12", children: [" ", _jsxs("div", { className: "space-y-8 sm:space-y-12", children: [_jsxs("div", { className: "fade-in flex flex-col items-center sm:flex-row sm:items-start gap-8", children: [_jsx("div", { className: "flex-shrink-0", children: _jsxs("div", { className: "relative", children: [_jsx("div", { className: "w-40 h-52 sm:w-56 sm:h-72 bg-gradient-to-br from-neutral-100 to-neutral-200 rounded-xl overflow-hidden shadow-2xl", children: _jsx("img", { src: "/bio/NK.png", alt: "Krishna Narayanan", className: "w-full h-full object-cover hover:scale-105 transition-transform duration-700" }) }), _jsx("div", { className: "absolute inset-0 rounded-xl ring-1 ring-inset ring-black/10" })] }) }), _jsxs("div", { className: "flex-1 space-y-2 pt-4 text-center sm:text-left", children: [" ", _jsx("h1", { className: "home-name text-white tracking-tight leading-tight", style: {
                                                        fontSize: '2.5rem', // Smaller on mobile
                                                        fontWeight: '200',
                                                        letterSpacing: '-0.025em',
                                                        textShadow: '0 4px 8px rgba(0,0,0,0.3)',
                                                        lineHeight: '1.1'
                                                    }, children: "Krishna Narayanan" }), _jsx("p", { className: "home-location text-white/90", style: {
                                                        fontSize: '1rem', // Smaller on mobile
                                                        fontWeight: '200',
                                                        textShadow: '0 2px 4px rgba(0,0,0,0.3)'
                                                    }, children: "Current affiliation: University of Southern Denmark, Odense, Denmark" })] })] }), _jsxs("div", { className: "fade-in space-y-6 bg-white/95 backdrop-blur-sm rounded-2xl p-5 sm:p-8 shadow-xl border border-white/50 -mt-24 sm:mt-0", children: [" ", _jsxs("div", { className: "prose-enhanced space-y-4 text-sm sm:text-base font-normal text-neutral-700", children: [_jsx("p", { children: "Welcome to my academic portfolio. I am currently a PhD Research Fellow at the University of Southern Denmark in Odense, where I am fortunate to be advised by Lars Rohwedder within the Algorithms unit at the Department of Mathematics and Computer Science. I recently defended my master's thesis in Mathematics at Simon Fraser University, Burnaby, BC, Canada under the supervision of Prof. Tamon Stephen, with a focus on Discrete Optimization. My master's work explored algorithmic questions in polytope theory and their computational complexity." }), _jsx("p", { children: "Before all this, I graduated with an Integrated Master's degree in Theoretical Computer Science from PSG College of Technology, Coimbatore, India (degree awarded by Anna University, Chennai), where I worked under the supervision of Prof. Lekshmi R S in the Department of Applied Mathematics and Computational Sciences." }), _jsx("p", { children: "My current focus is within the scope of hardness of approximation. More generally, my interests lie in or at the intersection of Combinatorial Optimization, Graph Theory, Polyhedral Combinatorics, and Computational Complexity Theory, in no particular order." })] }), _jsxs("div", { className: "pt-4 sm:pt-6 border-t border-neutral-200 space-y-3", children: [_jsxs("p", { className: "text-neutral-700 text-sm sm:text-base font-normal", children: ["I believe in keeping an open mind for good discussion and debate, as that's how I learn best. I have a variety of interests outside of academics; feel free to read more about them", ' ', _jsx(Link, { to: "/miscellaneous", className: "text-primary-600 hover:text-primary-700 underline decoration-primary-300 hover:decoration-primary-500 transition-colors duration-200", children: "here" }), "."] }), _jsxs("p", { className: "text-neutral-700 text-sm sm:text-base font-normal", children: ["Find a copy of my CV", ' ', _jsx("a", { href: "/bio/NK_CV_full-37.pdf", target: "_blank", rel: "noopener noreferrer", className: "text-primary-600 hover:text-primary-700 underline decoration-primary-300 hover:decoration-primary-500 transition-colors duration-200", children: "here" }), "."] }), _jsx("p", { className: "text-xs text-neutral-500 pt-1", children: "Last Updated: September 2026" })] })] })] })] }) })] }));
};
export default Home;
